server:
  port: 8082

spring:
  application:
    name: sarvatra-integration-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 50

rabbitmq:
  exchange: payment.hub.exchange

  queues:
    # MS2 listens on this queue (router sends here)
    from-router: ms2.transaction.request

    # MS2 sends response back to MS1 on this queue
    to-ms1: ms1.transaction.response

  routing-keys:
    from-router: ms2.txn.request
    to-ms1:      ms1.txn.response

logging:
  level:
    com.paymenthub.ms2: DEBUG
    org.springframework: INFO